In [1]:
import numpy as np
import gym
import random
import time

from IPython.display import clear_output

In [3]:
env = gym.make('FrozenLake-v1')

In [4]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n 

q_table = np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
num_episodes = 10000
max_steps_per_episode = 100

lr = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [ ]:
reward_all_episodes = []

## Q Learning Algorithem
for episode in range(num_episodes):
    state = env.reset()

    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode):
        #Explorartion-Exploitation tradeoff

        exploration_rate_threshold = random.uniform(0,1)

        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()

        new_state, reward, done, info = env.step(action)

        #updating Q table for Q(s,a)

        q_table[state, action] = q_table[state, action] * (1-lr) + lr*(reward+discount_rate* np.max(q_table[new_state,:]))

        state = new_state
        rewards_current_episode += reward

        if done ==True:
            break

        #exploration rate decay
        exploration_rate = min_exploration_rate + (max-exploration_rate-min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
        reward_all_episodes.append(rewards_current_episode)

#Avg reward per 1000 episodes
reward_per_1000_episodes = np.split(np.array(reward_all_episodes),num_episodes/1000)
count = 1000

print("***************Avg reward per 1000 episodes********************")
for r in reward_per_1000_episodes:
    print(count, ": ", str(sum(r/1000)))
    count+=1000

print("\n\n*****************Q-Table****************\n")
print(q_table)